apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scraper-service

resources:
- scraper-service-ns.yaml
- scraper-service-deployment.yaml
- scraper-service-svc.yaml
- ingress.yaml

images:
- name: usagre90/scraper-service
  newName: usagre90/scraper-service
  newTag: 9eb35087fce64309aade5b523b94d5af4c24e0f3
