apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  labels:
    env: common
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:pucksolutions/scheduling-engine.git
    targetRevision: main
    path: infrastructure/ingress 
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}