apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring 
  labels:
    env: common
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: git@github.com:4l3x7/scraper-service.git
    targetRevision: develop
    path: infrastructure/monitoring          
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}