
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scraper-service
  labels:
    env: integration
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: git@github.com:4l3x7/scraper-service.git
    targetRevision: main
    path: infrastructure/app         
  destination:
    server: https://kubernetes.default.svc
  syncPolicy: {}