apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zipkin 
  labels:
    env: common
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:pucksolutions/scheduling-engine.git
    targetRevision: develop
    path: kubernetes/integration-staging/zipkin
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}