apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- argocd-namespace.yaml
- deployment.yaml
- argo-application.yaml

patchesStrategicMerge:
- repository.yaml

patches:
  - path: applications/common-branch-patch.yaml
    target:
      kind: Application
