apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - name: scheduling-engine
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: repo-644572769
      type: git
      url: git@bitbucket.org:pucksolutions/scheduling-engine.git
---
