apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - name: scraper-service
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: repo-ssh-key
      type: git
      url: git@github.com:4l3x7/scraper-service.git