apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: argocd
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  data:
    sshPrivateKey: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEAo55Wj+mpOE/448uaytjVxJkX/nYlKHV2WaEpFD6Ws98gHzwnHAk2pddIRf5NOxwJJgxQWPoTZgVXzGU/C8eya4fSysMGgss7JzD8lQxvqfYSS2Q014Z33g1VwnYhsOqgbvLSOQgdpalGt8Oyt/OSNC7j4726QRqUM6WWlST5yLUTuxa4SXsLeGuFvTFvcLm72CrxXMEXYNQxqYSBuTexd9rPUtO0i0cwBXD27MvaoDVNi3NgWBrk9//k3MTFpoR0SMXJqONKx7AVFtLx1RqTHDqywb/cvArC+IqPAflCjN9y0+8uF7nN26WL3oXYoUCc+TtzWJoha0YylaSZFV12CQAAA9jf/8K73//CuwAAAAdzc2gtcnNhAAABAQCjnlaP6ak4T/jjy5rK2NXEmRf+diUodXZZoSkUPpaz3yAfPCccCTal10hF/k07HAkmDFBY+hNmBVfMZT8Lx7Jrh9LKwwaCyzsnMPyVDG+p9hJLZDTXhnfeDVXCdiGw6qBu8tI5CB2lqUa3w7K385I0LuPjvbpBGpQzpZaVJPnItRO7FrhJewt4a4W9MW9wubvYKvFcwRdg1DGphIG5N7F32s9S07SLRzAFcPbsy9qgNU2Lc2BYGuT3/+TcxMWmhHRIxcmo40rHsBUW0vHVGpMcOrLBv9y8CsL4io8B+UKM33LT7y4Xuc3bpYvehdihQJz5O3NYmiFrRjKVpJkVXXYJAAAAAwEAAQAAAQEAoztGFJECF4IBRhFMPm6Q5W/udhib/X8iMU0M1HuUkaJaQ48ZXWj7sfvSyLFpjzzrC6BhUEM8sx1FeE7R1QjHQWvhqhNjHX1vaCwA8RnVFPS/T6OK7DHkyAz5r+V2uy94Gvf5LpigKzNzr8V3OPmwtIrLI9uWQ3kmvVfHoMegws/7fEPPpCvirETqrP544AuE9x07F52g58WTyUzVkjlY97rR8FAbw1ajV3jqSikvl6zsFRTcpE0aGQolzS3PNzspyZEUNxhcSypSUwxBC46AZE3DFiqz4E7z71KWqBiaG0bRYKEUr9Smxxf24XWYkcLoRHCxBbCgJ/paWQ5l1UsS+QAAAIBbELIB9UeYCGffve8EfNZIatOEnIuRgPsZL8pMjpfwHapK/V3eUMEF9Kr4atOp+cw7f2ksfmy4DjNkADcAZ4aVzw/UCCl6x2z0bargeb4AV7b3hNrOoDXYet1nQj6o9f2OYtUg4v7mQrGp0j3gYBm2R+6eW5oVhiSus9gzRjJxLQAAAIEA0iRnnaxdZ/l41kvHuZMjefgT0MUlRxVQ5C5KBzuB+Pul7th4tvyh3Uhdiwkpgp6J/ssZCA9eCns/MHPi/STJI1tmX3ifitXhzyK3LVNKq0Pdrm1SWQZqSVSHUzbfOcbNko7R2KxT4aCzA8OClwDv+OyiuKCT4tG1TxAdfKcTNq8AAACBAMdS4wXwsmQirZbuwfcWTftjDba5Ezmbdup4ymQxPMyNM0/eOwZAbd6zKTM6eRtyYJgMcSxLHIml+0LLNVJdnzcBDGJ1cMmmHiCANXff5vXD7pKABfNdyM2oR0a/AX/PzM4Qt1rBsn+v6CXigMkcddhmvf+tIApFe8yCRmiebkzHAAAAIWFsZXhsb3BlekBBbGV4cy1NYWNCb29rLVByby5sb2NhbAE=
    kind: Secret  
    metadata:    
    annotations:
      managed-by: argocd.argoproj.io
    name: repo-ssh-key
    namespace: argocd
  type: Opaque
kind: List
metadata: {}