apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
data:
  GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-clock-panel,camptocamp-prometheus-alertmanager-datasource